name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        set +e
        TAG_VERSION=$(git describe --tags)
        set -e

        LD_FLAGS_VERSION="-X \"main.Version=${TAG_VERSION:-'v1.0.4'}\""

        go version
        mkdir out
        GOOS=darwin GOARCH=amd64 go build -ldflags "${LD_FLAGS_VERSION}" -o out/tanzu-apptx-cli-darwin_x64
        GOOS=linux GOARCH=amd64 go build -ldflags "${LD_FLAGS_VERSION}" -o out/tanzu-apptx-cli-linux_x64
        GOOS=windows GOARCH=amd64 go build -ldflags "${LD_FLAGS_VERSION}" -o out/tanzu-apptx-cli-windows_x64.exe
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: out
        retention-days: 5
