name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go version
        mkdir out
        env CGO_ENABLED=1 CC=o64-clang GOOS=darwin GOARCH=amd64 go build -o out/csa-darwin
        env CGO_ENABLED=1 CC=musl-gcc go build -o out/csa-linux
        env CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -o out/csa-windows.exe
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: out
        retention-days: 5
