name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        TAG_VERSION=$(git describe --tags)

        LD_FLAGS_VERSION="-X \"main.Version=${VERSION:v1.0.0-dev}\""

        go version
        mkdir out
        GOOS=darwin GOARCH=amd64 go build -ldflags "${LD_FLAGS}" -o out/iris-amd64-darwin
        GOOS=linux GOARCH=amd64 go build -ldflags "${LD_FLAGS}" -o out/iris-amd64-linux
        GOOS=windows GOARCH=amd64 go build -ldflags "${LD_FLAGS}" -o out/iris-amd64-windows.exe
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: out
        retention-days: 5
